/*==============================================================*/
/* uAchieve Release: uAchieve 4.0.7                                   */
/* DBMS name:      DB2                                       */
/* Created on:     7/23/2010                       */
/*                                                              */
/* Script name:    uadb2mod407.sql                               */
/* Purpose:        Updates DARwin 3.5.8 tables to their           */
/*                 uAchieve 4.0.7        */
/*                                                              */
/* Copyright(c) 2009-2010 redLantern, LLC, All Rights Reserved */
/*                                                              */
/*==============================================================*/

delete from job_queue_sysin
;
delete from job_queue_detail
;
delete from job_queue_list
;
commit;
Alter table JOB_QUEUE_LIST ADD column COMKEY char(10)
;
Alter table JOB_QUEUE_LIST ADD column LOG_LEVEL char(1)
;
Alter table JOB_QUEUE_LIST ADD column IGNORE_CACHE char(1)
;
Alter table JOB_QUEUE_LIST ADD column REPORT_TYPE char(3)
;
Alter table JOB_QUEUE_DETAIL ADD column STATUS char(1)
;
drop table job_queue_course
;
drop table job_queue_accept
;
drop table job_queue_subreq
;
drop table job_queue_req
;
drop table job_queue_run
;
create index job_q_list_idx on JOB_QUEUE_LIST (
SERVERNAME ASC,
STATUS ASC,
STARTDATE ASC,
STARTTIME ASC,
PRIORITY ASC,
JOBID ASC
)
;
CREATE TABLE JOB_QUEUE_RUN
(
   INT_SEQ_NO           NUMERIC(9)             NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   INSTIDQ              CHAR(2)                DEFAULT ' ',
   INSTID               CHAR(8)                DEFAULT ' ',
   INSTCD               CHAR(3)                DEFAULT ' ',
   JOBID                CHAR(16)               DEFAULT ' ',
   USERID               CHAR(30)               DEFAULT ' ',
   SOPRID               CHAR(8)                DEFAULT ' ',
   STUNO                CHAR(13)               DEFAULT ' ',
   DPROG                CHAR(15)               DEFAULT ' ',
   DPMASK               CHAR(15)               DEFAULT ' ',
   CATLYT               CHAR(6)                DEFAULT ' ',
   BINSTID              CHAR(8),
   BINSTCD              CHAR(3),
   RUNDATE              TIMESTAMP,
   JOBQ_SYSOUT_USED     CHAR(1),  
   NCOL                 CHAR(1),
   COMPLETE             CHAR(1),
   IP                   CHAR(1),
   DPTITLE1             CHAR(65),
   DPTITLE2             CHAR(65),
   WEBTITLE				      CHAR(50),
   DETAIL_SEQ_NO		    NUMERIC(9),
   ALTSTUNO             CHAR(13),
   FIRSTNAME            VARCHAR(30),
   MIDDLENAME           VARCHAR(15),
   LASTNAME             VARCHAR(30),
   PREFIXNAME           VARCHAR(4),
   SUFFIXNAME           VARCHAR(6),
   STUNAME              VARCHAR(60),
   LISTALL              CHAR(1),
   TESTSTATUS           CHAR(1),
   REPORT_TYPE			CHAR(3),
   CONSTRAINT P_KEY_23 PRIMARY KEY (INT_SEQ_NO)
)
;
--==============================================================
-- INDEX: JOBQ_RUN_IDX
--==============================================================
CREATE INDEX JOBQ_RUN_IDX ON JOB_QUEUE_RUN (
   STUNO                ASC,
   INSTIDQ              ASC,
   INSTID               ASC,
   INSTCD               ASC,
   SOPRID               ASC,
   DPROG                ASC,
   DPMASK               ASC,
   CATLYT               ASC,
   USERID               ASC
)
;
CREATE TABLE JOB_QUEUE_OUT
(
   INT_SEQ_NO           NUMERIC(9)             NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   JOBQ_SEQ_NO          NUMERIC(9)             NOT NULL DEFAULT 0,
   USER_SEQ_NO          INTEGER                DEFAULT 0,
   RTABX                CHAR(2),
   REQSTATUS            CHAR(1),
   STABX                CHAR(3),
   SRNO                 CHAR(2),
   SRSTATUS             CHAR(1),
   OPTLINE              CHAR(1),
   LASERA               CHAR(1),
   LASERB               CHAR(1),
   DAROUT               VARCHAR(255),
   CONSTRAINT P_KEY_22 PRIMARY KEY (INT_SEQ_NO)
);

--==============================================================
-- INDEX: JOB_Q_OUT_IDX
--==============================================================
CREATE INDEX JOB_Q_OUT_IDX ON JOB_QUEUE_OUT (
   JOBQ_SEQ_NO          ASC,
   USER_SEQ_NO          ASC,
   RTABX                ASC,
   STABX                ASC,
   OPTLINE              ASC
);

--==============================================================
-- TABLE: JOB_QUEUE_REQ
--==============================================================
CREATE TABLE JOB_QUEUE_REQ
(
   JOBQ_SEQ_NO          NUMERIC(9)             NOT NULL,
   RTABX                CHAR(3)                NOT NULL,
   RNO                  CHAR(3),
   RNAME                VARCHAR(9),
   PSNAME               VARCHAR(15),
   CATEGORY             VARCHAR(15),
   SUMMARY_GRP          VARCHAR(15),
   TRANSCRIPT           CHAR(1),
   TOTAL_HOUR           CHAR(1),
   TOTAL_GPA            CHAR(1),
   HIDEFROMCHART        CHAR(1),
   SATISFIED            CHAR(1),
   SUMMARY              CHAR(1),
   SORTFLG              CHAR(1),
   ORREQ                CHAR(1),
   OPTREQ               CHAR(1),
   REQSRQ               INTEGER,
   GOTSRQ               INTEGER,
   NEEDSRQ              INTEGER,
   REQCT                INTEGER,
   GOTCT                INTEGER,
   IPCT                 INTEGER,
   WHATIFCT             INTEGER,
   NEEDCT               INTEGER,
   MAXHRS               NUMERIC(10,5),
   REQHRS               NUMERIC(10,5),
   EST_REQHRS           NUMERIC(10,5),
   GOTHRS               NUMERIC(10,5),
   IPHRS                NUMERIC(10,5),
   WHATIFHRS            NUMERIC(10,5),
   NEEDHRS              NUMERIC(10,5),
   GOTGPAHRS            NUMERIC(10,5),
   GOTGPAPTS            NUMERIC(10,5),
   REQGPA               NUMERIC(10,5),
   GOTGPA               NUMERIC(10,5),
   NEEDGPA              NUMERIC(10,5),
   REQGPAF              CHAR(1),
   GPANAME              CHAR(15),
   GPALOWYT				CHAR(6),
   GPAHIGHYT            CHAR(6),
   HIDDEN				CHAR(1),
   HIDECATEGORYGPA      CHAR(1),
   GROUP1				CHAR(1),
   GROUP2				CHAR(1),
   REUSE				CHAR(1),
   LABEL                VARCHAR(25),
   hideheadtitle 		char(1),
   hideneedssummary char(1),
   hideselfrmcrs char(1),
   hidemtchdcrs char(1),
   CONSTRAINT P_KEY_1 PRIMARY KEY (JOBQ_SEQ_NO, RTABX)
)
;
--==============================================================
-- INDEX: JOBQ_REQ_IDX
--==============================================================
CREATE INDEX JOBQ_REQ_IDX ON JOB_QUEUE_REQ (
   JOBQ_SEQ_NO          ASC,
   RTABX                ASC,
   RNAME                ASC,
   CATEGORY             ASC,
   SUMMARY_GRP          ASC,
   TRANSCRIPT           ASC,
   TOTAL_HOUR           ASC,
   HIDEFROMCHART        ASC,
   SUMMARY              ASC
);

ALTER TABLE JOB_QUEUE_REQ
   ADD CONSTRAINT FK_JOBQ_REQ_REF_JO FOREIGN KEY (JOBQ_SEQ_NO)
      REFERENCES JOB_QUEUE_RUN (INT_SEQ_NO)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

--==============================================================
-- TABLE: JOB_QUEUE_SUBREQ
--==============================================================
CREATE TABLE JOB_QUEUE_SUBREQ
(
   JOBQ_SEQ_NO          NUMERIC(9)             NOT NULL,
   RTABX                CHAR(3)                NOT NULL,
   STABX                CHAR(3)                NOT NULL,
   SNO                  CHAR(3),
   SATISFIED            CHAR(1),
   SORTFLG              CHAR(1),
   ORSUB                CHAR(1),
   OPTSUB               CHAR(1),
   REQCT                INTEGER,
   GOTCT                INTEGER,
   NEEDCT               INTEGER,
   IPCT                 INTEGER,
   WHATIFCT             INTEGER,
   MAXHRS               NUMERIC(10,5),
   REQHRS               NUMERIC(10,5),
   EST_REQHRSFLG        CHAR(1),
   EST_REQHRS           NUMERIC(10,5),
   GOTHRS               NUMERIC(10,5),
   IPHRS                NUMERIC(10,5),
   WHATIFHRS            NUMERIC(10,5),
   NEEDHRS              NUMERIC(10,5),
   REQGPA               NUMERIC(10,5),
   GOTGPA               NUMERIC(10,5),
   NEEDGPA              NUMERIC(10,5),
   GOTGPAHRS            NUMERIC(10,5),
   GOTGPAPTS            NUMERIC(10,5)          DEFAULT 0,
   REQGPAF              CHAR(1),
   GPANAME              CHAR(15),
   GPALOWYT		          CHAR(6),
   GPAHIGHYT            CHAR(6),
   HIDDEN	              CHAR(1),
   SUBREQ_ID            NUMERIC(9),
   REUSE				        CHAR(1),   
   LABEL 				        VARCHAR(25),
   STITLE               VARCHAR(55),
   hidetitle char(1),
   hidesummary char(1),
   hideselfrmcrs char(1),
   hidestucrs char(1),
   CONSTRAINT P_KEY_1 PRIMARY KEY (JOBQ_SEQ_NO, RTABX, STABX)
)
;

ALTER TABLE JOB_QUEUE_SUBREQ
   ADD CONSTRAINT FK_JOBQ_SUBREQ_REF FOREIGN KEY (JOBQ_SEQ_NO, RTABX)
      REFERENCES JOB_QUEUE_REQ (JOBQ_SEQ_NO, RTABX)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

--==============================================================
-- TABLE: JOB_QUEUE_ACCEPT
--==============================================================
CREATE TABLE JOB_QUEUE_ACCEPT
(
   INT_SEQ_NO           NUMERIC(9) 			   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   JOBQ_SEQ_NO          NUMERIC(9)             NOT NULL,
   RTABX                CHAR(3)                NOT NULL,
   STABX                CHAR(3)                NOT NULL,   
   COURSE               VARCHAR(15),
   TITLE                VARCHAR(29),
   REJECT               CHAR(1),
   USED                 CHAR(1),
   LOGIC                CHAR(1),
   REQUIRED             CHAR(1),
   CMPRTITLE            CHAR(1),
   RANGECOURSE          CHAR(15),
   LOWYT                CHAR(6),
   HIGHYT               CHAR(6),
   HIDDEN				        CHAR(1),
   INNER_MEM 			      CHAR(1),
   INNER_BGN 			      CHAR(1),
   INNER_END 			      CHAR(1),
   OUTER_MEM 			      CHAR(1),
   OUTER_BGN 			      CHAR(1),
   OUTER_END 			      CHAR(1),
   SYMBOL_BEFORE 		    CHAR(5),
   USER_SEQ_NO          NUMERIC(9),
   DEPT                 CHAR(15),
   CRSNO                CHAR(15),
   PSEUDO_FLAG          CHAR(1),
   CONSTRAINT P_KEY_1 PRIMARY KEY (INT_SEQ_NO)
);
--==============================================================
-- INDEX: JOBQ_ACCEPT_IDX
--==============================================================
CREATE INDEX JOBQ_ACCEPT_IDX ON JOB_QUEUE_ACCEPT (
   JOBQ_SEQ_NO          ASC,
   RTABX                ASC,
   STABX                ASC,  
   REJECT               ASC
);

ALTER TABLE JOB_QUEUE_ACCEPT
   ADD CONSTRAINT F_REFERENCE_43 FOREIGN KEY (JOBQ_SEQ_NO, RTABX, STABX)
      REFERENCES JOB_QUEUE_SUBREQ (JOBQ_SEQ_NO, RTABX, STABX)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

--==============================================================
-- TABLE: JOB_QUEUE_COURSE
--==============================================================
CREATE TABLE JOB_QUEUE_COURSE
(
   INT_SEQ_NO           NUMERIC(9) 			   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   JOBQ_SEQ_NO          NUMERIC(9)             NOT NULL,
   RTABX                CHAR(3)                NOT NULL,
   STABX                CHAR(3)                NOT NULL,   
    USER_SEQ_NO          NUMERIC(9),
   YT                   CHAR(6),
   EDIT_YT              CHAR(4),
   COURSE               VARCHAR(15),
   XCOURSE              VARCHAR(15),
   RCREDIT              NUMERIC(10,5),
   CREDIT               NUMERIC(10,5),
   GPAHRS               NUMERIC(10,5),
   GPAPTS               NUMERIC(10,5),
   GPA                  NUMERIC(10,5),
   GRADE                CHAR(4),
   RGRADE               CHAR(4),
   IP                   CHAR(1),
   WHATIF               CHAR(1),
   CTITLE               VARCHAR(29),
   RTITLE               VARCHAR(29),
   STITLE               VARCHAR(29),
   CVTTITLE             VARCHAR(29),
   ALTTITLE             VARCHAR(29),
   CONSTRAINT P_KEY_1 PRIMARY KEY (INT_SEQ_NO)
);
ALTER TABLE JOB_QUEUE_COURSE
   ADD CONSTRAINT FK_JOBQ_CRS_REF_JO FOREIGN KEY (JOBQ_SEQ_NO, RTABX, STABX)
      REFERENCES JOB_QUEUE_SUBREQ (JOBQ_SEQ_NO, RTABX, STABX)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

--===================================================
-- New  Tables u.achieve 4.0
--===================================================
--====================================================
-- JOB_QUEUE_MARKERS 
--====================================================
CREATE TABLE JOB_QUEUE_MARKERS (
   INT_SEQ_NO NUMERIC(9) NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   JOBQ_SEQ_NO NUMERIC(9),
   USER_SEQ_NO NUMERIC(9),
   RNAME  CHAR(9),
   DRVAL  CHAR(15),
   DRTYPE CHAR(1),
   CATLYT CHAR(6),
   TITLE1   VARCHAR(80),
   TITLE2   VARCHAR(80),
   WEBTITLE VARCHAR(80),
   CONSTRAINT PK_J_Q_MARKER PRIMARY KEY (INT_SEQ_NO)
)
;
ALTER TABLE JOB_QUEUE_MARKERS
   ADD CONSTRAINT FK_JQMRK_REF_JQRUN FOREIGN KEY (JOBQ_SEQ_NO)
      REFERENCES JOB_QUEUE_RUN (INT_SEQ_NO)
;
--==============================================================*/
-- Index: jq_markers_idx                                        */
--==============================================================*/
CREATE INDEX JQ_MARKERS_IDX ON JOB_QUEUE_MARKERS (
    JOBQ_SEQ_NO ASC
)
;
--==============================================================--
-- JOB_QUEUE_EXCEPTIONS                                         --
--==============================================================--
CREATE TABLE JOB_QUEUE_EXCEPTIONS (
   INT_SEQ_NO  NUMERIC(9) NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   JOBQ_SEQ_NO NUMERIC(9),
   USER_SEQ_NO NUMERIC(9),
   CTLCD   CHAR(2),
   ACTION  CHAR(1),
   RUFLG CHAR(1),
   MEMO VARCHAR(255),
   LAST_MOD_USER VARCHAR(30) ,
   LAST_MOD_DATE DATE,
CONSTRAINT PK_J_Q_EXCEPTION PRIMARY KEY  (INT_SEQ_NO)
)
;
ALTER TABLE JOB_QUEUE_EXCEPTIONS
   ADD CONSTRAINT FK_JQEXC_REF_JQRUN FOREIGN KEY (JOBQ_SEQ_NO)
      REFERENCES JOB_QUEUE_RUN (INT_SEQ_NO)
;
--==============================================================--
-- INDEX: JQ_EXCEPTIONS_IDX                                     --
--==============================================================--
CREATE INDEX JQ_EXCEPTIONS_IDX ON JOB_QUEUE_EXCEPTIONS (
    JOBQ_SEQ_NO ASC
)
;
--==============================================================--
-- JOB_QUEUE_REQ_TEXT                                           --
--==============================================================--
CREATE TABLE JOB_QUEUE_REQ_TEXT (
   JOBQ_SEQ_NO NUMERIC(9) NOT NULL,
   TEXT_TYPE CHAR(1) NOT NULL DEFAULT 'T',
   RTABX CHAR(3) NOT NULL,   
   TEXT CLOB,
   CONSTRAINT PK_J_Q_REQ_TEXT PRIMARY KEY  (JOBQ_SEQ_NO, TEXT_TYPE, RTABX)
)
;

ALTER TABLE JOB_QUEUE_REQ_TEXT
   ADD CONSTRAINT FK_JQRTXT_REF_JQRQ FOREIGN KEY (JOBQ_SEQ_NO, RTABX)
      REFERENCES JOB_QUEUE_REQ (JOBQ_SEQ_NO, RTABX)
;
--==============================================================--
-- INDEX: JQ_REQ_TEXT_IDX                                       --
--==============================================================--
CREATE INDEX JQ_REQ_TEXT_IDX ON JOB_QUEUE_REQ_TEXT (
    JOBQ_SEQ_NO ASC,
    RTABX ASC
)
;
--==============================================================--
-- JOB_QUEUE_SUBREQ_TEXT                                        --
--==============================================================--
CREATE TABLE JOB_QUEUE_SUBREQ_TEXT (
   JOBQ_SEQ_NO NUMERIC(9) NOT NULL,
   TEXT_TYPE CHAR(1) NOT NULL DEFAULT 'T',
   RTABX  CHAR(3) NOT NULL,  
   STABX  CHAR(3) NOT NULL,  
   TEXT CLOB,
   CONSTRAINT PK_J_Q_SUBREQ_TEXT PRIMARY KEY  (JOBQ_SEQ_NO, TEXT_TYPE, RTABX, STABX)
)
;
ALTER TABLE JOB_QUEUE_SUBREQ_TEXT
   ADD CONSTRAINT FK_JQSRT_REF_JQREQ FOREIGN KEY (JOBQ_SEQ_NO, RTABX, STABX)
      REFERENCES JOB_QUEUE_SUBREQ (JOBQ_SEQ_NO, RTABX, STABX)
;
--==============================================================--
-- INDEX: JQ_SUBREQ_TEXT_IDX                                    --
--==============================================================--
CREATE INDEX JQ_SUBREQ_TEXT_IDX ON JOB_QUEUE_SUBREQ_TEXT (
    JOBQ_SEQ_NO ASC,
    RTABX ASC,
    STABX ASC
)
;
--==============================================================--
-- JOB_QUEUE_REPORT                                             --
--==============================================================--
CREATE TABLE JOB_QUEUE_REPORT(
	INT_SEQ_NO NUMERIC(9) NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	JOBQ_SEQ_NO NUMERIC(9),
	REPORT_TYPE CHAR(3),
	REPORT BLOB,
	CONSTRAINT PK_J_Q_REPORT PRIMARY KEY (INT_SEQ_NO)) 
;
ALTER TABLE JOB_QUEUE_REPORT
   ADD CONSTRAINT FK_JQREP_REF_JQRUN FOREIGN KEY (JOBQ_SEQ_NO)
      REFERENCES JOB_QUEUE_RUN (INT_SEQ_NO)
;
--==============================================================--
-- INDEX: JQ_REPORT_IDX                                        --
--==============================================================--
CREATE INDEX JQ_REPORT_IDX ON JOB_QUEUE_REPORT (
    JOBQ_SEQ_NO ASC
)
;
--==============================================================--
-- JOB_QUEUE_INCL_TEXT                                          --
--==============================================================--
CREATE TABLE JOB_QUEUE_INCL_TEXT(
INT_SEQ_NO NUMERIC(9) NOT NULL GENERATED BY DEFAULT AS IDENTITY,
JOBQ_SEQ_NO NUMERIC(9),
TEXT_TYPE CHAR(1),
TEXT CLOB,
CONSTRAINT PK_QUEUE_INCL_TEXT
PRIMARY KEY
(INT_SEQ_NO)
)
;

ALTER TABLE JOB_QUEUE_INCL_TEXT
ADD CONSTRAINT FK_JQINCL_REF_JQR FOREIGN KEY (JOBQ_SEQ_NO)
REFERENCES JOB_QUEUE_RUN (INT_SEQ_NO)
;
--==============================================================--
-- INDEX: JQ_INCL_TEXT_IDX                                      --
--==============================================================--
CREATE INDEX JQ_INCL_TEXT_IDX ON JOB_QUEUE_INCL_TEXT (
    JOBQ_SEQ_NO ASC
)
;
--==============================================================--
-- INCLUDE_TEXT                                                 --
--==============================================================--
CREATE TABLE INCLUDE_TEXT
(INSTIDQ CHAR(2) DEFAULT ' ' NOT NULL,
INSTID CHAR(8) DEFAULT ' ' NOT NULL,
INSTCD CHAR(3) DEFAULT ' ' NOT NULL,
TEXT_KEY VARCHAR(20) DEFAULT ' ' NOT NULL,
TEXT_TYPE CHAR(1) NOT NULL DEFAULT 'T',
TEXT CLOB,
LAST_MOD_USER VARCHAR(30),
LAST_MOD_DATE DATE,
CONSTRAINT pk_incl_text PRIMARY KEY
(INSTIDQ, INSTID, INSTCD, TEXT_KEY, TEXT_TYPE)
)
;

CREATE TABLE CURRENT_JOBS (
	INSTCD VARCHAR(3)  NOT NULL,
	INSTID VARCHAR(8)  NOT NULL,
	INSTIDQ VARCHAR(2)  NOT NULL,
	STUNO VARCHAR(15)  NOT NULL,
	STARTTIME TIMESTAMP,
 CONSTRAINT PK_CURRENT_JOBS PRIMARY KEY (instcd, instid , instidq, stuno)
);

