alter table dprog add column type_code char(3)
;



/*==============================================================*/
/* Table: DPROG_TYPE                                            */
/*==============================================================*/
CREATE TABLE dprog_type (
   instidq              char(2)               not null,
   instid               char(8)               not null,
   instcd               char(3)               not null,
   type_code            char(3)               not null,
   label	            	varchar(30)           ,
   type_order           int                   not null,
   constraint PK_dprog_type primary key (instidq, instid, instcd, type_code)
)
;

ALTER TABLE dprog_type
	ADD 
	UNIQUE (instidq, instid, instcd, type_order)
;

/*==============================================================*/
/* Table: WHATIF_ELEMENT_TYPE_ASSOC                             */
/*==============================================================*/
CREATE TABLE whatif_element_type_assoc ( 
	int_seq_no    	numeric(18) 			NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	instidq		       	char(2) 				NOT NULL,
	instid		       	char(8) 				NOT NULL,
	instcd	        	char(3) 				NOT NULL,
	element		       	char(15)				NOT NULL,
	dprog_type		   	char(3) 				NOT NULL,
	label	         	varchar(30) 			,
	forced_mapping		char(1) 				NOT NULL  DEFAULT 'N',
	reqd_values		   	int 					NOT NULL  DEFAULT 0,
	max_values	    	int 					NOT NULL  DEFAULT 0,
	parent_element		char(15) 				NOT NULL,
	fyt		           	char(6) 				NOT NULL,
	lyt		           	char(6) 				NOT NULL,
	group_order		   	int 					NOT NULL,
	forced_catalog_year	char(1)					NOT NULL  DEFAULT 'N',
	CONSTRAINT pk_weta PRIMARY KEY (int_seq_no)
)
;


ALTER TABLE whatif_element_type_assoc
	ADD
	UNIQUE (instidq, instid, instcd, element, dprog_type, fyt, parent_element)	
;

ALTER TABLE whatif_element_type_assoc
	ADD CONSTRAINT fk_weta_rel_dpr
	FOREIGN KEY(instidq, instid, instcd, dprog_type)
	REFERENCES dprog_type(instidq, instid, instcd, type_code)
	 ON DELETE RESTRICT ON UPDATE RESTRICT;


/*==============================================================*/
/* Table: WHATIF_FORCED_MARKER	                                */
/*==============================================================*/
CREATE TABLE whatif_forced_marker  ( 
	int_seq_no	     	numeric(18) 		NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	weta_int_seq_no		numeric(18) 		NOT NULL,
	element_value	  	char(15) 			NOT NULL,
	forced_marker	  	char(9) 			NOT NULL,
	forced_val	     	char(15)			NOT NULL,
	forced_type	    	char(1) 			NOT NULL,
	fyt	            	char(6) 			NOT NULL,
	lyt	            	char(6) 			NOT NULL,
	exclude 	       	char(1) 			NOT NULL,
	ref_instidq	    	varchar(2) 			NOT NULL,
	ref_instid 	    	varchar(8) 			NOT NULL,
	ref_instcd	     	varchar(3) 			NOT NULL,
	CONSTRAINT pk_wi_forced_mar PRIMARY KEY(int_seq_no)
	)
;
ALTER TABLE whatif_forced_marker
	ADD CONSTRAINT fk_wi_ele_typ
	FOREIGN KEY(weta_int_seq_no)
	REFERENCES whatif_element_type_assoc(int_seq_no)
	 ON DELETE RESTRICT ON UPDATE RESTRICT;
;

/*==============================================================*/
/* Table: WHATIF_ELEMENT_FILTER	                                */
/*==============================================================*/
CREATE TABLE whatif_element_filter  ( 
	int_seq_no    	numeric(18) 		NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	instidq       	char(2) 			NOT NULL,
	instid        	char(8) 			NOT NULL,
	instcd        	char(3) 			NOT NULL,
	dprog         	char(15) 			NOT NULL,
	element       	char(15) 			NOT NULL,
	filter_pattern	char(25) 			NOT NULL,
	fyt           	char(6) 			NOT NULL,
	lyt           	char(6) 			NOT NULL,
	exclude       	char(1) 			NOT NULL,
	ref_instidq   	varchar(2) 			NOT NULL,
	ref_instid    	varchar(8) 			NOT NULL,
	ref_instcd    	varchar(3) 			NOT NULL,
	CONSTRAINT pk_wi_elemf PRIMARY KEY (int_seq_no)
	)
;