ALTER TABLE JOB_QUEUE_REQ
ADD COLUMN  GROUP1           CHAR(1)
;
ALTER TABLE JOB_QUEUE_REQ
ADD COLUMN  GROUP2           CHAR(1)
;

ALTER TABLE JOB_QUEUE_REQ
ADD COLUMN  REUSE           CHAR(1)
;

ALTER TABLE JOB_QUEUE_SUBREQ
ADD COLUMN  REUSE           CHAR(1)
;

CREATE INDEX jobq_sysin_idx ON JOB_QUEUE_SYSIN (INSTIDQ, INSTID, INSTCD, JOBID, USERID);