ALTER TABLE JOB_QUEUE_SUBREQ
 ADD STITLE VARCHAR(55);

ALTER TABLE REQ_MAIN
 ADD AUTH_CODE1  VARCHAR(10);
 
ALTER TABLE REQ_MAIN
ADD  AUTH_CODE2  VARCHAR(10);
 
ALTER TABLE STU_EXCEPTIONS
ADD  AUTH_CODE  VARCHAR(10);

CREATE TABLE ADV_AUTHCODES(
 ADV_ID CHAR(20) NOT NULL CONSTRAINT PK_ADV_AUTH_CDS PRIMARY KEY,
 AUTH_CODE VARCHAR(10), 
 CONSTRAINT FK_ADV_AUTH_CDS  FOREIGN KEY(ADV_ID)
 REFERENCES ADV_MASTER(ADV_ID));