CREATE TABLE JOB_QUEUE_DESTINATION (
 JOBID CHAR(16) NOT NULL,
 USERID VARCHAR(30) NOT NULL,
 DESTINATION_URL VARCHAR(255) NOT NULL,
 OUTPUT_FORMAT CHAR(1),
 SEND_ERROR_COUNT INTEGER DEFAULT 0 NOT NULL,
 SEND_ERROR_MESSAGE VARCHAR(255),
 STATUS CHAR(1) NOT NULL,
 SEND_DATE DATE,
 NEXT_SEND_DATE DATE
)
;
ALTER TABLE JOB_QUEUE_DESTINATION ADD PRIMARY KEY (JOBID, USERID)
;
CREATE INDEX IX_JOB_QUEUE_DEST ON JOB_QUEUE_DESTINATION 
 (STATUS, NEXT_SEND_DATE)
;
Alter table adv_master
 add userid char(30)
;


Drop Table adv_authcodes;


CREATE TABLE ADV_AUTHCODES(
 ADV_ID CHAR(20) not null ,
 AUTH_CODE VARCHAR(10) Not null, 
 CONSTRAINT PK_ADV_AUTH_CDS PRIMARY KEY (ADV_ID, AUTH_CODE),
 CONSTRAINT FK_ADV_AUTH_CDS  FOREIGN KEY(ADV_ID)
 REFERENCES ADV_MASTER(ADV_ID));