CREATE VIEW VW_RED_PROPERTY_DOMAIN_MAPPING AS 
SELECT MAPPING_ID, ENTITY_ID, ENTITY_TYPE, PROPERTY_ID, VALUE, 
INSTIDQ, INSTID, INSTCD, DESCRIPTION FROM RED_PROPERTY_DOMAIN_MAPPING
;
	
	
CREATE VIEW VW_RED_USER_GROUP AS SELECT USER_ID, GROUP_ID 
	FROM RED_USER_GROUP
;
Alter table job_queue_run ADD column graddate varchar(80)